### ISSUE TITLE
A more convenient single bracket escape

### ISSUE THREAD

**Issue by eugenesvk** [xigoi/xidoc#9]
`;[` or `/[` or `\[`  or `[[`
`;]` or `/]` or `\]`  or `]]`
(the `;` without a space afterwards is a rare typing occurrence and is the most convenient due to the home row position of <kbd>;</kbd>)
... instead of the current 3-char implementation `[(]`
Would those break anything fundamental in parsing?

**Comment by xigoi** [comment]
I wanted xidoc to have as few special characters as possible. Making `\` an escape character would mean that you'd have to also escape `\`, which often leads to “backslash soup”. Same for `/`. `;]` and `]]` would be ambiguous, since they already mean “last argument to the command is empty” and “close two commands” respectively.

Also, allowing unpaired brackets would make parsing a lot harder. With the xidoc syntax, you can find the end of a command simply by finding the matching bracket. If brackets were allowed to be escaped, that would be an undecidable problem.

`[(]` and `[)]` are not that inconvenient. In most cases, you can just use `[()]`.

**Comment by eugenesvk** [comment]
But you wouldn't need to escape `\`, only `\[` if you meant it literally, it's not a universal escape character, rather a very limited one, so paths can stay as is unless some folder name starts with a `[`, so there is no soup (same with `/`)
The parsing challenge is real, through maybe worth it for convenience :)

And `[(` is twice stretching your pinky finger AND another pinky-hold for a shift, so that's one of the more inconvenient key combos
Plus you'd have to delete two `)]  autocompletions, which is two more pinky moves
Besides, it's also counterintuitive to read ( to as [

**Comment by xigoi** [comment]
> But you wouldn't need to escape \, only \[ if you meant it literally

Then how would you produce a backslash followed by an opening bracket?

> The parsing challenge is real, through maybe worth it for convenience :)

Not just parsing, I'd have to fundamentally change how xidoc works. That's not worth it.

> And [( is twice stretching your pinky finger AND another pinky-hold for a shift

Interesting. I press the square brackets with my ring finger.

> Plus you'd have to delete two `)] autocompletions, which is two more pinky moves

With my setup, I just press `[<c-v>(]`. And, again, I use the `[(]` and `[)]` commands very rarely in practice.

> Besides, it's also counterintuitive to read ( to as [

You get used to it.

**Comment by eugenesvk** [comment]
> Then how would you produce a backslash followed by an opening bracket?

by escaping `\[` like so: `\\[`
Why does the need to escape one sequence `\[` imply the need to escape every `\`? Is there some parsing bug I'm missing?

> Interesting. I press the square brackets with my ring finger.

That's not quite right ![proper finger map](http://mail.onlinetyping.org/typing-lessons/images/touch-typing-keyboard.png)

> > Plus you'd have to delete two `)] autocompletions, which is two more pinky moves
> 
> With my setup, I just press `[<c-v>(]`. And, again, I use the `[(]` and `[)]` commands very rarely in practice.

correction: you don't delete 2 autocompletions, but just the 1st `)`, you then type `]` (or <kbd>⇥</kbd> in some editors) to move to the end of the 2nd `]`
What do you mean "just" when <kbd>^</kbd><kbd>v</kbd> is slightly worse than <kbd>⌦</kbd> as it involes a separate key combo with another corner key

**Comment by xigoi** [comment]
> Why does the need to escape one sequence \[ imply the need to escape every \? Is there some parsing bug I'm missing?

I didn't say you'd have to escape *every* backslash.

> That's not quite right

The “correct” way to type was designed for secretaries typing on a typewriter, who usually had average-sized fingers and rarely needed to use brackets. I have long fingers and need brackets often, so it makes more sense for me to have a more stretched layout in order to avoid straining my pinkies.

By the way, get a foot switch if you can, it really helps with those annoying corner keys.

If you want xidoc's syntax to be different, feel free to make a fork and see how it goes. I just recently updated the parser and I don't think there are going to be any major changes anytime soon.
